cc_library(
    name = "mobil",
    srcs = [
        "mobil.cpp"
    ],
    hdrs = [
        "mobil.hpp"
    ],
    deps = [
        "//modules/models/behavior/idm:idm_classic",
        "//modules/models/behavior/pure_pursuit:pure_pursuit",
    ],
    visibility = ["//visibility:public"]
)