# cc_library(
#     name = "mpc",
#     srcs = [
#         "mpc.cpp",
#     ],
#     hdrs = [
#         "mpc.hpp",
#         "cost_functor.hpp",
#         "common.hpp",
#     ],
#     deps = [
#         "//modules/commons:commons",
#         "//modules/models/dynamic:dynamic",
#         "//modules/models/execution:execution",
# 	    "@com_github_eigen_eigen//:eigen",
#         "@com_google_ceres_solver//:ceres",
#     ],
#     visibility = ["//visibility:public"],
#     copts=
#     [
#         "-O3" # optimized build to reduce ceres run time
#     ],
#     linkstatic = 1
# )

#cpplint()
