cc_library(
    name="include",
    deps=[
        "//modules/commons:include",
        "//modules/geometry:include",
        "//modules/models:include",
        "//modules/world:include"
    ],
    visibility = ["//visibility:public"],
)