cc_library(
    name = "interpolation",
    srcs = [
        "interpolate.cpp",
    ],
    hdrs = [
        "interpolate.hpp",
    ],
    deps = [
        "//modules/commons:commons",
        "//modules/models/dynamic:dynamic",
        "//modules/models/execution:execution",
	      "@com_github_eigen_eigen//:eigen",
    ],
    visibility = ["//visibility:public"]
)

#cpplint()
