cc_library(
    name="include",
    deps= [
        "//bark/models/behavior:include",
        "//bark/models/observer:include",
        "//bark/models/dynamic:include",
        "//bark/models/execution:include",
    ],
    visibility = ["//visibility:public"],
)