
cc_library(
    name = "param_config",
    hdrs = [
           "behav_macro_actions_from_param_server.hpp"
    ],
    deps= [
        "//bark:include",
    ],
    visibility = ["//visibility:public"],
)
cc_library(
    name="include",
    hdrs=glob(["*.hpp"]),
    visibility = ["//visibility:public"],
)
