py_library(
    name = "scenario",
    srcs = ["scenario.py"],
    data = ['//python:bark.so'],
    imports = ['../../../python'],
    deps = ["//modules/runtime/commons:parameters",
            "//modules/runtime/commons:commons",],
    visibility = ["//visibility:public"],
)