# Copyright (c) 2019 fortiss GmbH
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

py_library(
    name = "scenario",
    srcs = ["scenario.py"],
    data = ['//python:bark.so'],
    imports = ['../../../python'],
    deps = ["//modules/runtime/commons:parameters",
            "//modules/runtime/commons:commons",],
    visibility = ["//visibility:public"],
)