cc_library(
    name = "not_started",
    srcs = [],
    hdrs = ["behavior_not_started.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//bark/models/behavior",
        "//bark/world",
    ],
)

cc_library(
    name = "include",
    hdrs = glob(["*.hpp"]),
    visibility = ["//visibility:public"],
)
