py_library(
    name = "runners",
    srcs = ["base_runner.py",
            "tfa_runner.py"],
    data = ['//python:bark.so'],
    imports = ['../../../python'],
    visibility = ["//visibility:public"],
)