cc_library(
    name = "behavior",
    hdrs = [
        "behavior_model.hpp",
    ],
    deps = [
        "//modules/commons:commons",
        "//modules/models/dynamic:dynamic"
    ],
    visibility = ["//visibility:public"],
)

#cpplint()
