cc_library(
    name = "goal_definition",
    srcs = [],
    hdrs = [
        "goal_definition.hpp"
    ],
    deps = [
        "//modules/geometry",
        "@boost//:geometry",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"],
)
