name: ManyLinux

on: [push]

jobs:
  build_py36:
    runs-on: ubuntu-latest
    container:
      image: docker://barksim/bazel-manylinux
    steps:
      - uses: actions/checkout@v1
      - name: Setting up virtual environment
        run: virtualenv --python=/opt/python/cp36-cp36m/bin/python ./bark/python_wrapper/venv
      - name: Getting into venv
        run: . ./bark/python_wrapper/venv/bin/activate
      - name: Installing Requirements
        run: ./bark/python_wrapper/venv/bin/pip3 install --upgrade pip && ./bark/python_wrapper/venv/bin/pip3 install -r ./tools/installers/requirements.txt
      - name: Building ManyLinux
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: bash package.sh manylinux

  build_py37:
    runs-on: ubuntu-latest
    container:
      image: docker://barksim/bazel-manylinux
    steps:
      - uses: actions/checkout@v1
      - name: Setting up virtual environment
        run: virtualenv --python=/opt/python/cp37-cp37m/bin/python ./bark/python_wrapper/venv
      - name: Getting into venv
        run: . ./bark/python_wrapper/venv/bin/activate
      - name: Installing Requirements
        run: ./bark/python_wrapper/venv/bin/pip3 install --upgrade pip && ./bark/python_wrapper/venv/bin/pip3 install -r ./tools/installers/requirements.txt
      - name: Building ManyLinux
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: bash package.sh manylinux

  build_py38:
    runs-on: ubuntu-latest
    container:
      image: docker://barksim/bazel-manylinux
    steps:
      - uses: actions/checkout@v1
      - name: Setting up virtual environment
        run: virtualenv --python=/opt/python/cp38-cp38m/bin/python ./bark/python_wrapper/venv
      - name: Getting into venv
        run: . ./bark/python_wrapper/venv/bin/activate
      - name: Installing Requirements
        run: ./bark/python_wrapper/venv/bin/pip3 install --upgrade pip && ./bark/python_wrapper/venv/bin/pip3 install -r ./tools/installers/requirements.txt
      - name: Building ManyLinux
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: bash package.sh manylinux