
cc_library(
    name = "param_config",
    hdrs = [
           "behav_macro_actions_from_param_server.hpp"
    ],
    deps= [
        "//modules:include",
    ],
    visibility = ["//visibility:public"],
)
