cc_library(
    name = "behavior_action_store",
    srcs = [
        "behavior_action_store.cpp",
    ],
    hdrs = [
        "behavior_action_store.hpp",
    ],
    deps = [
        "//modules/models/behavior:behavior",
        "//modules/models/dynamic:dynamic",
    ],
    visibility = ["//visibility:public"],
)


cc_library(
    name="include",
    hdrs=glob(["*.hpp"]),
    visibility = ["//visibility:public"],
)