py_library(
    name = "agents",
    srcs = ["base_agent.py",
            "sac_agent.py"],
    data = ['//python:bark.so'],
    imports = ['../../../python'],
    visibility = ["//visibility:public"],
)