# py_library(
#   name = "init_py",
#   srcs = ["__init__.py"],
#   visibility = ["//visibility:public"],
# )

cc_library(
    name="include",
    deps=[
        "//bark/commons:include",
        "//bark/geometry:include",
        "//bark/models:include",
        "//bark/world:include"
    ],
    visibility = ["//visibility:public"],
)
