package(default_visibility = ["//visibility:public"])

py_test(
  name = "py_pickle_tests",
  srcs = ["py_pickle_tests.py"],
  data = ['//bark:generate_core'],
  deps = ["//bark/runtime/commons:commons"]
)