py_library(
    name = "scenario",
    srcs = ["scenario.py"],
    data = ['//bark/pybark:core.so'],
    imports = ['../../../python'],
    deps = ["//bark/runtime/commons:parameters",
            "//bark/runtime/commons:commons",],
    visibility = ["//visibility:public"],
)