py_library(
    name = "scenario",
    srcs = ["scenario.py","__init__.py"],
    data = ['//bark:generate_core'],
    deps = ["//bark/runtime/commons:commons",],
    visibility = ["//visibility:public"],
)