cc_library(
    name = "dynamic",
    hdrs = [
        "integration.hpp",
        "single_track.hpp",
        "dynamic_model.hpp",
    ],
    deps = [
        "//modules/commons:commons",
	    "@com_github_eigen_eigen//:eigen",
        "@boost//:geometry",
    ],
    visibility = ["//visibility:public"]
)