cc_library(
    name = "execution",
    hdrs = [
        "execution_model.hpp",
    ],
    deps = [
        "//bark/commons:commons",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name="include",
    hdrs=glob(["*.hpp"]),
    visibility = ["//visibility:public"],
)

#cpplint()
