cc_library(
    name = "timer",
    hdrs = [
        "timer.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = ["@boost//:date_time"],
)

cc_library(
    name="include",
    hdrs=glob(["*.hpp"]),
    visibility = ["//visibility:public"],
)
