py_library(
    name = "parameters",
    srcs = ["parameters.py","__init__.py"],
    data = ['//bark/core:core.so'],
    imports = ['../../core'],
    deps = [],
    visibility = ["//visibility:public"],
)

py_library(
    name = "commons",
    srcs = ["commons.py","__init__.py"],
    data = ['//bark/core:core.so'],
    imports = ['../../core'],
    deps = [],
    visibility = ["//visibility:public"],
)

py_library(
    name = "xodr_parser",
    srcs = ["xodr_parser.py","__init__.py"],
    data = ['//bark/core:core.so'],
    imports = ['../../core'],
    deps = [],
    visibility = ["//visibility:public"],
)

py_library(
    name = "model_json_conversion",
    srcs = ["model_json_conversion.py","__init__.py"],
    data = ['//bark/core:core.so'],
    imports = ['.../../core'],
    deps = [],
    visibility = ["//visibility:public"],
)
