cc_library(
    name = "predictor",
    srcs = [
        "prediction.cpp"
    ],
    hdrs = [
        "commons.hpp",
        "prediction.hpp",
    ],
    deps = [
        "//modules/commons:commons",
        "//modules/models/behavior:behavior",
        "//modules/models/behavior/idm:idm_classic",
        "//modules/world:world",
    ],
    visibility = ["//visibility:public"],
)
