cc_library(
    name = "nop",
    srcs = [],
    hdrs = [
        "nop.hpp",
    ],
    deps = [
        "//modules/world:world",
        "//modules/models/behavior:behavior",
        "//modules/models/dynamic:dynamic"
    ],
    visibility = ["//visibility:public"],
)