package(default_visibility = ["//visibility:public"])

cc_library(
    name = "math",
    hdrs = [
        "vector.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = []
)

cc_library(
    name="include",
    hdrs=glob(["*.hpp"]),
    visibility = ["//visibility:public"],
)
