package(default_visibility = ["//visibility:public"])

cc_library(
    name = "params",
    hdrs = [
        "params.hpp",
        "params_test.h",
        "default_params.hpp",
    ],
    visibility = ["//visibility:public"],
)
