package(default_visibility = ["//visibility:public"])

cc_library(
    name = "params",
    hdrs = [
        "params.hpp",
        "params_test.h",
        "default_params.hpp",
        "setter_params.hpp"
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name="include",
    hdrs=glob(["*.hpp"]),
    visibility = ["//visibility:public"],
)
