cc_library(
    name = "state_delta",
    srcs = [
        "state_delta.cpp",
    ],
    hdrs = [
        "state_delta.hpp",
    ],
    deps = [
        "//modules/commons:commons",
        "//modules/world:world",
        "//modules/models/behavior:behavior",
        "//modules/models/dynamic:dynamic"
    ],
    visibility = ["//visibility:public"],
)
