cc_library(
    name = "primitive",
    hdrs = ["primitive.hpp"],
    deps = [],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "object_primitive",
    hdrs = ["object_primitive.hpp"],
    deps = ["//bark/world/renderer:primitive"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "renderer",
    hdrs = ["renderer.hpp"],
    deps = ["//bark/world/renderer:primitive"],
    visibility = ["//visibility:public"],
)