cc_library(
    name = "constant_velocity",
    srcs = [
        "constant_velocity.cpp",
    ],
    hdrs = [
        "constant_velocity.hpp",
    ],
    deps = [
        "//modules/commons:commons",
        "//modules/world:world",
        "//modules/models/behavior:behavior",
        "//modules/models/dynamic:dynamic"
    ],
    visibility = ["//visibility:public"],
)
