cc_library(
    name = "hypothesis",
    hdrs = [
        "behavior_hypothesis.hpp",
    ],
    deps = [
        "//modules/models/behavior:behavior",
        "//modules/commons/distribution:distribution"
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name="include",
    hdrs=glob(["*.hpp"]),
    visibility = ["//visibility:public"],
)